name = "NYC Taxi Panel DeckGL"
description = "A Panel application that uses the NYC Taxi dataset and DeckGL to generate a data visualisation on a map."
packages = ["bokeh==3.2.2", "numpy", "pandas", "panel"]
